
import agro from '../../assets/images/default/people/agro.webp';
import biotech from '../../assets/images/default/people/biotech.webp';
import education from '../../assets/images/default/people/education.webp';
import energetics from '../../assets/images/default/people/energetics.webp';
import geology from '../../assets/images/default/people/geology.webp';
import himtech from '../../assets/images/default/people/himtech.webp';
import machine from '../../assets/images/default/people/machine.webp';
import materials from '../../assets/images/default/people/materials.webp';
import infosec from '../../assets/images/default/people/infosec.webp';
import it from '../../assets/images/default/people/it.webp';
import safetech from '../../assets/images/default/people/safetech.webp';
import service from '../../assets/images/default/people/serviceMain.webp';
import techcontrol from '../../assets/images/default/people/techcontrol.webp';
import transportMain from '../../assets/images/default/people/transportMain.webp';
import techprom from '../../assets/images/default/people/techpromMain.webp';
import stroy from '../../assets/images/default/people/stroy.webp';
import economy from '../../assets/images/default/people/economy.webp';
import pravo from '../../assets/images/default/people/pravo.webp';
import radioelectronic from '../../assets/images/default/people/radioelectronicShown.webp';
import trade from '../../assets/images/default/people/trade.webp';

import agroMountin from '../../assets/images/mountins/agroMountin.webp';
import biotechMountin from '../../assets/images/mountins/biotechMountin.webp';
import economyMountin from '../../assets/images/mountins/economyMountin.webp';
import educationMountin from '../../assets/images/mountins/eductionMountin.webp';
import electricsMountin from '../../assets/images/mountins/electricsMountin.webp';
import geologyMountin from '../../assets/images/mountins/geologyMountin.webp';
import himtechMountin from '../../assets/images/mountins/himTechMountin.webp';
import infosecMountin from '../../assets/images/mountins/infosecMountin.webp';
import itMountin from '../../assets/images/mountins/itMountin.webp';
import machineMountin from '../../assets/images/mountins/machineMountin.webp';
import materialsMountin from '../../assets/images/mountins/materialsMountin.webp';
import pravoMountin from '../../assets/images/mountins/pravoMountin.webp';
import radioelectronicMoutin from '../../assets/images/mountins/radioelectronicMoutin.webp';
import safetechMountin from '../../assets/images/mountins/safetechMountin.webp';
import serviceMountin from '../../assets/images/mountins/serviceMountin.webp';
import stroyMountin from '../../assets/images/mountins/stroyMountin.webp';
import techcontrolMountin from '../../assets/images/mountins/techcontrolMountin.webp';
import techpromMountin from '../../assets/images/mountins/techpromMountin.webp';
import transportMountin from '../../assets/images/mountins/transportMountin.webp';
import tradeMountin from '../../assets/images/mountins/tradeMountin.webp';

export const jobs = [
  {
    id: 'education',
    type: 'motion',
    position: { top: 368, left: 1083, width: 187, height: 249 },
    spaceTopSmall: 0,
    text: {
      content: 'Образование\nи педагогические\nнауки',
      isRight: true,
      top: 54,
      width: 194,
      height: 48,
      spacing: 148,
    },
    person: {
      src: education,
      width: 134,
      height: 200,
      top: 0,
      left: 48,
      isMirror: false,
    },
    mountain: {
      src: educationMountin,
      width: 187,
      height: 206,
      top: 40,
      left: 0,
    },
    modal: {
      top: 75,
      right: -300,
      width: 380,
      paddingTop: 40,
      isMirror: true,
    },
    hasCircle: false,
  },
  {
    id: 'techcontrol',
    type: 'motion',
    position: { top: 460, left: 0, width: 201, height: 213 },
    spaceTopSmall: 0,
    text: {
      content: 'Управление\nв технических системах',
      isRight: true,
      top: 51,
      width: 229,
      spacing: 140,
    },
    person: {
      src: techcontrol,
      width: 146,
      height: 218,
      top: -30,
      left: 85,
      isMirror: true,
    },
    mountain: {
      src: techcontrolMountin,
      width: 200,
      height: 200,
      top: 13,
      left: 0,
    },
    modal: {
      width: 380,
      top: 10,
      right: -230,
      paddingTop:100,
      isMirror: true,
    },
    hasCircle: false,
  },
  {
    id: 'pravo',
    type: 'motion',
    position: { top: 683, left: 205, width: 219, height: 191 },
    spaceTopSmall: 0,
    text: {
      content: 'юриспруденция',
      isRight: false,
      top: 40,
      width: 181,
      height: 30,
      spacing: -24,
    },
    person: {
      src: pravo,
      width: 104,
      height: 184,
      top: 0,
      left: 141,
      isMirror: false,
    },
    mountain: {
      src: pravoMountin,
      width: 219,
      height: 179,
      top: 54,
      left: 0,
    },
    modal: {
      width: 480,
      top: -25,
      height: 230,
      right: -270,
      isMirror: true,
    },
    hasCircle: false,
  },
  {
    id: 'radioelectronic',
    type: 'motion',
    position: { top: 713, left: 1146, width: 251, height: 192 },
    spaceTopSmall: 60,
    text: {
      content: 'Электроника,\nрадиотехника\nи системы связи',
      isRight: false,
      top: 70,
      width: 164,
      spacing: 119,
    },
    person: {
      src: radioelectronic,
      width: 83,
      height: 175,
      top: 0,
      left: 13,
      isMirror: true,
    },
    mountain: {
      src: radioelectronicMoutin,
      width: 251,
      height: 192,
      top: 1,
      left: 0,
    },
    modal: {
      width: 460,
      top: -25,
      height: 230,
      right: 140,
      isMirror: false,
    },
    hasCircle: false,
  },
  {
    id: 'geology',
    type: 'absolute',
    position: { top: 580, left: 633, width: 327, height: 206 },
    text: {
      content: 'Прикладная геология,\nгорное дело, нефтегазовое\nдело и геодезия',
      isRight: true,
      top: 40,
      width: 233,
      spacing: 150,
    },
    person: {
      src: geology,
      width: 106 * 1.3,
      height: 170 * 1.3,
      top: -25,
      left: 168,
      isMirror: false,
    },
    mountain: {
      src: geologyMountin,
      width: 327,
      height: 206,
      top: 0,
      left: 0,
    },
    modal: {
      width: 485,
      top: -35,
      height: 230,
      right: -135,
      isMirror: false,
    },
    hasCircle: false,
  },
  {
    id: 'trade',
    type: 'absolute',
    position: { top: 775, left: 465, width: 306, height: 208 },
    text: {
      content: 'Торговое дело\nи логистика',
      isRight: true,
      top: 48,
      width: 165,
      spacing: 60,
    },
    person: {
      src: trade,
      width: 146,
      height: 185,
      top: 0,
      left: 160,
      isMirror: false,
    },
    mountain: {
      src: tradeMountin,
      width: 250,
      height: 172,
      top: 36,
      left: 0,
    },
    modal: {
      width: 415,
      top: -20,
      height: 230,
      right: -35,
      isMirror: false,
    },
    hasCircle: false,
  },
  {
    id: 'stroy',
    type: 'absolute',
    position: { top: 900, left: 780, width: 306, height: 208 },
    text: {
      content: 'Техника\nи технологии\nстроительства',
      isRight: true,
      top: 44,
      width: 157,
      spacing: 30,
    },
    person: {
      src: stroy,
      width: 77,
      height: 175,
      top: 0,
      left: 140,
      isMirror: false,
    },
    mountain: {
      src: stroyMountin,
      width: 233,
      height: 156,
      top: 43,
      left: 0,
    },
    modal: {
      width: 430,
      top: -25,
      height: 230,
      right: -15,
      isMirror: false,
    },
    hasCircle: false,
  },
  {
    id: 'economy',
    type: 'absolute',
    position: { top: 1067, left: 506, width: 342, height: 180 },
    text: {
      content: 'Экономика\nи финансы',
      isRight: false,
      top: 48,
      width: 157,
      spacing: 45,
    },
    person: {
      src: economy,
      width: 95,
      height: 168,
      top: 0,
      left: 59,
      isMirror: false,
    },
    mountain: {
      src: economyMountin,
      width: 342,
      height: 155,
      top: 25,
      left: 0,
    },
    modal: {
      width: 380,
      top: -25,
      height: 230,
      right: -15,
      isMirror: true,
    },
    hasCircle: false,
  },
  {
    id: 'service',
    type: 'absolute',
    position: { top: 1254, left: 292, width: 251, height: 222 },
    text: {
      content: 'Сервис\nи туризм',
      isRight: true,
      top: 48,
      width: 131,
      spacing: 0,
    },
    person: {
      src: service,
      width: 98,
      height: 185,
      top: 0,
      left: 68,
      isMirror: false,
    },
    mountain: {
      src: serviceMountin,
      width: 258,
      height: 139,
      top: 83,
      left: 0,
    },
    modal: {
      width: 380,
      top: -25,
      height: 230,
      right: 35,
      isMirror: false,
    },
    hasCircle: false,
  },
  {
    id: 'infosec',
    type: 'absolute',
    position: { top: 1125, left: 21, width: 261, height: 235 },
    text: {
      content: 'Информационная\nбезопасность',
      isRight: true,
      top: 30,
      width: 204,
      spacing: 30,
    },
    person: {
      src: infosec,
      width: 175,
      height: 230,
      top: -20,
      left: 15,
      isMirror: false,
    },
    mountain: {
      src: infosecMountin,
      width: 261,
      height: 169,
      top: 66,
      left: 0,
    },
    modal: {
      width: 530,
      top: -20,
      height: 230,
      right: -305,
      isMirror: true,
    },
    hasCircle: false,
  },
  {
    id: 'machine',
    type: 'absolute',
    position: { top: 1461, left: 14, width: 312, height: 202 },
    text: {
      content: 'машиностроение',
      isRight: false,
      top: 16,
      width: 175,
      height: 30,
      spacing: -21,
    },
    person: {
      src: machine,
      width: 117,
      height: 181,
      top: 0,
      left: 145,
      isMirror: false,
    },
    mountain: {
      src: machineMountin,
      width: 312,
      height: 142,
      top: 60,
      left: 0,
    },
    modal: {
      width: 450,
      top: -25,
      height: 230,
      right: -175,
      isMirror: true,
    },
    hasCircle: false,
  },
  {
    id: 'safetech',
    type: 'absolute',
    position: { top: 1809, left: 2, width: 283, height: 194 },
    text: {
      content: 'Техносферная\nбезопасность\nи природообустройство',
      isRight: true,
      top: 7,
      width: 184,
      spacing: -5,
    },
    person: {
      src: safetech,
      width: 96 * 1.45,
      height: 180 * 1.45,
      top: -42,
      left: 31,
      isMirror: false,
    },
    mountain: {
      src: safetechMountin,
      width: 283,
      height: 141,
      top: 53,
      left: 0,
    },
    modal: {
      width: 515,
      top: -20,
      height: 220,
      right: -265,
      isMirror: true,
    },
    hasCircle: false,
  },
  {
    id: 'energetics',
    type: 'absolute',
    position: { top: 1976, left: 855, width: 320, height: 218 },
    text: {
      content: 'Электро-\nи теплоэнергетика',
      isRight: true,
      top: 40,
      width: 180,
      spacing: 65,
    },
    person: {
      src: energetics,
      width: 120 * 1.35,
      height: 200 * 1.35,
      top: -42,
      left: 121,
      isMirror: false,
    },
    mountain: {
      src: electricsMountin,
      width: 320,
      height: 192,
      top: 26,
      left: 0,
    },
    modal: {
      width: 485,
      top: -25,
      height: 230,
      right: -35,
      isMirror: false,
    },
    hasCircle: false,
  },
  {
    id: 'it',
    type: 'absolute',
    position: { top: 1796, left: 1109, width: 305, height: 209 },
    text: {
      content: 'Информатика\nи вычислительная\nтехника',
      isRight: false,
      top: 33,
      width: 173,
      spacing: 8,
    },
    person: {
      src: it,
      width: 104 * 1.35,
      height: 189 * 1.35,
      top: -42,
      left: 80,
      isMirror: false,
    },
    mountain: {
      src: itMountin,
      width: 305,
      height: 162,
      top: 47,
      left: 0,
    },
    modal: {
      width: 455,
      top: -25,
      height: 230,
      right: 75,
      isMirror: false,
    },
    hasCircle: false,
  },
  {
    id: 'biotech',
    type: 'absolute',
    position: { top: 1283, left: 858, width: 270, height: 202 },
    text: {
      content: 'Промышленная экология\nи биотехнологии',
      isRight: true,
      top: 18,
      width: 203,
      spacing: 18,
    },
    person: {
      src: biotech,
      width: 92 * 1.45,
      height: 188 * 1.45,
      top: -42,
      left: 10,
      isMirror: false,
    },
    mountain: {
      src: biotechMountin,
      width: 270,
      height: 141,
      top: 61,
      left: 0,
    },
    modal: {
      width: 460,
      top: -13,
      height: 210,
      right: 0,
      isMirror: false,
    },
    hasCircle: false,
  },
  {
    id: 'materials',
    type: 'absolute',
    position: { top: 1440, left: 518, width: 251, height: 206 },
    text: {
      content: 'Технологии\nматериалов',
      isRight: true,
      top: 49,
      width: 135,
      spacing: 67,
    },
    person: {
      src: materials,
      width: 83,
      height: 189,
      top: 0,
      left: 154,
      isMirror: false,
    },
    mountain: {
      src: materialsMountin,
      width: 251,
      height: 192,
      top: 14,
      left: 0,
    },
    modal: {
      width: 400,
      top: -6,
      height: 200,
      right: -48,
      isMirror: false,
    },
    hasCircle: false,
  },
  {
    id: 'agro',
    type: 'absolute',
    position: { top: 1590, left: 808, width: 342, height: 213 },
    text: {
      content: 'Сельское, лесное\nи рыбное хозяйство',
      isRight: true,
      top: 70,
      width: 201,
      spacing: 0,
    },
    person: {
      src: agro,
      width: 109 * 1.4,
      height: 182 * 1.4,
      top: -40,
      left: 90,
      isMirror: true,
    },
    mountain: {
      src: agroMountin,
      width: 221,
      height: 221,
      top: -7,
      left: -2,
    },
    modal: {
      width: 470,
      top: -25,
      height: 230,
      right: 115,
      isMirror: false,
    },
    hasCircle: false,
  },
  {
    id: 'himtech',
    type: 'absolute',
    position: { top: 1679, left: 283, width: 261, height: 196 },
    text: {
      content: 'химические\nтехнологии',
      isRight: true,
      top: 49,
      width: 155,
      spacing: 71,
    },
    person: {
      src: himtech,
      width: 84 * 1.2,
      height: 183 * 1.2,
      top: -45,
      left: 130,
      isMirror: true,
    },
    mountain: {
      src: himtechMountin,
      width: 261,
      height: 169,
      top: 27,
      left: 0,
    },
    modal: {
      width: 410,
      top: -25,
      height: 210,
      right: -42,
      isMirror: false,
    },
    hasCircle: true,
  },
  {
    id: 'transport',
    type: 'absolute',
    position: { top: 1844, left: 591, width: 260, height: 208 },
    text: {
      content: 'Техника и технологии\nназемного транспорта',
      isRight: false,
      top: 55,
      width: 192,
      spacing: 116,
    },
    person: {
      src: transportMain,
      width: 112,
      height: 180,
      top: 0,
      left: 23,
      isMirror: false,
    },
    mountain: {
      src: transportMountin,
      width: 260,
      height: 132,
      top: 75,
      left: 0,
    },
    modal: {
      width: 490,
      top: -15,
      height: 210,
      right: -128,
      isMirror: true,
    },
    hasCircle: false,
  },
  {
    id: 'techprom',
    type: 'absolute',
    position: { top: 1978, left: 245, width: 347, height: 236 },
    text: {
      content: 'Технологии легкой\nпромышленности',
      isRight: false,
      top: 74,
      width: 161,
      spacing: 29,
    },
    person: {
      src: techprom,
      width: 128,
      height: 200,
      top: 0,
      left: 101,
      isMirror: false,
    },
    mountain: {
      src: techpromMountin,
      width: 347,
      height: 139,
      top: 97,
      left: 0,
    },
    modal: {
      width: 470,
      top: -10,
      height: 210,
      right: -108,
      isMirror: true,
    },
    hasCircle: false,
  },
];